# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LuaViewDemo' do
	pod 'RCExtension', '~> 1.0.0'
	pod 'AFNetworking', '~> 3.1.0'
	pod 'SDWebImage', '~> 3.8.1'
	pod 'LuaViewSDK', :git => 'https://github.com/alibaba/LuaViewSDK.git'
end
