# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RXCollectionsDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RXCollectionsDemo
  pod 'ReactiveObjC', '~> 3.0.0'
  pod 'BlocksKit', '~> 2.2.5'

end
